const express = require('express')
const router = express.Router()
//导入路由处理函数
const course_handler = require('../router_handler/artcate')

router.post('/getcourse',course_handler.getCourse)
router.post('/gethomework0',course_handler.getHomework0)
router.post('/gethomework1',course_handler.getHomework1)
router.post('/gettask0',course_handler.getTask0)
router.post('/gettask1',course_handler.getTask1)
router.post('/addcourse',course_handler.addCourse)
router.post('/course',course_handler.Course)
router.post('/submithomework',course_handler.submitHomework)
router.post('/obtainhomework',course_handler.obtainHomework)
router.post('/obtaintask',course_handler.obtainTask)
router.post('/updatehomework',course_handler.updateHomework)
router.post('/updatetask',course_handler.updateTask)
router.post('/homeworktopic',course_handler.homeworkTopic)
router.post('/getstudent0',course_handler.getStudent0)
router.post('/getstudent1',course_handler.getStudent1)
router.post('/getstudent2',course_handler.getStudent2)
router.post('/getstudent3',course_handler.getStudent3)
router.post('/getstudent4',course_handler.getStudent4)
router.post('/gethomework',course_handler.getHomework)
router.post('/gettask',course_handler.getTask)
router.post('/getusertask',course_handler.getUserTask)
router.post('/usertask',course_handler.UserTask)
router.post('/task',course_handler.Task)
router.post('/admincourse',course_handler.adminCourse)
router.post('/adminpersonnel',course_handler.adminPersonnel)
router.post('/updatepeople',course_handler.updatePeople)
router.post('/updatecourse',course_handler.updateCourse)
router.post('/viewpeople',course_handler.viewPeople)
router.post('/viewcourse',course_handler.viewCourse)
router.post('/deletepeople',course_handler.deletePeople)
router.post('/deletecourse',course_handler.deleteCourse)
router.post('/publishjob',course_handler.publishJob)
router.post('/publishtask',course_handler.publishTask)
router.post('/publishcourse',course_handler.publishCourse)
router.post('/deletecourses',course_handler.deleteCourses)
router.post('/revisetask',course_handler.reviseTask)
router.post('/revisehomework',course_handler.reviseHomework)
router.post('/homework',course_handler.homework)
router.post('/xghomework',course_handler.xgHomework)
router.post('/hdtask',course_handler.hdTask)
router.post('/xgtask',course_handler.xgTask)
router.post('/getscore',course_handler.getScore)
router.post('/getstudent9',course_handler.getStudent9)
module.exports = router